{% set name = "SimSIMD" %}
{% set version = "6.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ashvardanian/SimSIMD/archive/v{{ version }}.tar.gz
  sha256: 1c2cfa9ab66de4337ea27c22068d1a8b44c0cb8df4c4b661fc273e1645a8221b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]
  host:
    - python
    - setuptools
    - wheel
    - pip
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]
  run:
    - python

test:
  requires:
    - pip
  imports:
    - simsimd
  commands:
    - pip check


about:
  home: https://github.com/ashvardanian/SimSIMD
  summary: Portable mixed-precision BLAS-like vector math library for x86 and ARM
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mukhery
