{% set name = "SimSIMD" %}
{% set version = "6.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ashvardanian/SimSIMD/archive/v{{ version }}.tar.gz
  sha256: 73cbedd8ebdfdea9d4bc5715d1da2c41c8ac5194ddf717fea3c63431d54f1e6a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]
  host:
    - python
    - setuptools
    - wheel
    - pip
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]
  run:
    - python

test:
  requires:
    - pip
  imports:
    - simsimd
  commands:
    - pip check


about:
  home: https://github.com/ashvardanian/SimSIMD
  summary: Portable mixed-precision BLAS-like vector math library for x86 and ARM
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mukhery
