{% set name = "SimSIMD" %}
{% set version = "6.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ashvardanian/SimSIMD/archive/v{{ version }}.tar.gz
  sha256: def29210bddbd1651fe33f002a42687c0fb59c97c81613e37e81ce201a82b6f2

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]
  host:
    - python
    - setuptools
    - wheel
    - pip
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]
  run:
    - python

test:
  requires:
    - pip
  imports:
    - simsimd
  commands:
    - pip check


about:
  home: https://github.com/ashvardanian/SimSIMD
  summary: Portable mixed-precision BLAS-like vector math library for x86 and ARM
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mukhery
